Deepseek/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
       path('admin/', admin.site.urls),
       path('',include('base.urls')),
       path('api/v1/',include('base.api.urls')),
]

base/api/urls.py
from django.urls import path, include
from . import views

urlpatterns = [  
       path('recipes/', views.getRecipes),
       path('shops/', views.getShops),
       path('posts/', views.getPosts), 
]

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
       path('register/',views.createUser, name='register'), 
       path('logout/',views.logoutUser, name='logout'), 
       path('login/',views.loginUser, name='login'), 
       path('',views.home, name='home'), 
       path('recipes/',views.recipes, name='recipes'), 
       path('recipe/<str:pk>/',views.recipe, name='recipe'),    
       path('create-recipe/',views.createRecipe, name='create-recipe'),
       path('update-recipe/<str:pk>/',views.updateRecipe, name='update-recipe'),
       path('cart/',views.cart, name='cart'),
       path('my-shop/',views.shops, name='shops'),
       path('my-shop/<str:pk>/',views.shop, name='shop'),
       path('shop/create-shop/',views.createShop, name='create-shop'),
       path('shop/update-shop/<str:pk>/',views.updateShop, name='update-shop'),
       path('shop/delete-shop/<str:pk>/',views.deleteShop, name='delete-shop'),
       path('about/',views.about, name='about'),
       path('forum/',views.forum, name='forum'),
       path('abstract/',views.createWithAbstractUser, name='abstractUser'),
       path('create-post/',views.createPost, name='create-post'),
       path('post/<str:pk>/',views.readPost, name='read-post'),
       path('recipe/buy/<str:pk>/',views.buyRecipe, name='buy-recipe'),
]

base/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User, AbstractBaseUser, BaseUserManager
# from django.contrib.auth.models import  

class MyUserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, date_of_birth, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        unique=True,
    )
    username = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["date_of_birth"]

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff login
        return self.is_admin



class Customer(models.Model):
    genderClass = {
        'M':'Male',
        'F':'Female'
    }
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    location = models.CharField(max_length=100) 
    gender = models.CharField(max_length=1, choices=genderClass)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name
         
# representation of your table in your DB

"""
#SQL 

CREATE TABLE recipe ( 
    name VARCHAR(255),
    description LONGTEXT,  
    prepTime INT,
    cookTime INT, 
    level VARCHAR(100),
    ingredients LONGTEXT,
    steps LONGTEXT 
    );

    CRUD ===> DBs
    SCHEMA=> blueprint of a table-> class
    from the schema we create a table and create records 
"""
class Recipe(models.Model):    
    cookingLevels = { 
        "B": "Beginner",  
        "I": "Intermediate",
        "P":"Pro"
    }
    name = models.CharField(max_length=255) # "Coaching Rugby by Antony"
    decription = models.TextField() #  
    prepTime = models.IntegerField()
    cookTime = models.IntegerField()
    level = models.CharField(max_length=1, choices=cookingLevels) 
    ingredients = models.TextField() 
    steps = models.TextField() 
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # organize from the latest to the oldest
    class Meta:
        ordering =['-updated_at','-created_at']

    def __str__(self):
        return self.name
    

class Shop(models.Model):
    productName = models.CharField(max_length=150) 
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        ordering =['-updated_at','-created_at']

    def __str__(self):
        return self.productName
    
"""
========================================================================
"""

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # one to one relationship
    bio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE) #one to many relationship
    title = models.CharField(max_length = 100)
    content = models.TextField()
    contributors = models.ManyToManyField(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        ordering =['-updated_at', '-created_at']
    
    def __str__(self):
        return f"Post by {self.author.user.username}"

class Comment(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE) #one to many relationship
    post = models.ForeignKey(Post, on_delete=models.CASCADE) #one to many relationship 
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        ordering =['-updated_at', '-created_at']
    
    def __str__(self):
        return f"by {self.author.user.username}"

base/api/views.py
from base.models import Recipe, Author, Post, Shop
from rest_framework.response import Response
from rest_framework.decorators import   api_view
from .serializers import RecipeSerializer, ShopSerializer, PostSerializer


@api_view(['GET'])
def getShops(request):
    shops = Shop.objects.all()
    serializer = ShopSerializer(shops, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def getPosts(request):
    posts = Post.objects.all()
    serializer = PostSerializer(posts, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getPost(request, id):
    posts = Post.objects.get(id=id)
    serializer = PostSerializer(post, many=True)
    return Response(serializer.data)

















@api_view(['GET'])
def getRecipes(request):
    recipes = Recipe.objects.all()
    serializer = RecipeSerializer(recipes,many=True )
    return Response(serializer.data)

base/views.py
from django.shortcuts import render, redirect
from .models import Recipe, Shop , Author, Comment, Post
from .forms import RecipeForm, ShopForm, PostForm,AuthorForm, CommentForm, UserCreationForm
from django.contrib import messages

# authentication 
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.forms import UserCreationForm

# MPESA

from django_daraja.mpesa.core import MpesaClient


def createWithAbstractUser(request):
    form = UserCreationForm()  
    context = {"form":form}


    return render(request, 'base/abstract.html', context)
def createUser(request):
    form = UserCreationForm()  
    bio  = AuthorForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)  
        bio  = AuthorForm(request.POST)

        if form.is_valid() and bio.is_valid():
            user = form.save()
            authorBio = bio.cleaned_data['bio']

            Author.objects.create(
                user = user,
                bio = authorBio
            )

            messages.info(request, "Welcome home!")

            return redirect('login')
        else:
            messages.error(request, "Something went wrong!")

    context = {"form":form, "bio":bio} 
    return render(request, 'base/register.html', context)

def loginUser(request):  
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # checked wheyther the user exists in the DB => Users table
        try:
            user = User.objects.get(username = username)
        except:
            messages.error(request, "User does not exist!")
        # authenticated the user and checked whether the credentials are ok
        user = authenticate(request, username=username, password=password) 
        if user is not None: 
            login(request, user)
            messages.error(request, f"Welcome home {user.username}!")
            return redirect('home')
        else:
            messages.error(request, "Wrong Credentials")
        
    return render(request, "base/login.html")

def logoutUser(request):
    if request.method == "POST":
        logout(request)
        messages.info(request, "See you soon!")
        return redirect('login')
    return render(request, "base/logout_form.html")

def home(request):
    recipes = Recipe.objects.all()
    context = {"recipes":len(recipes)}
    # cl = MpesaClient()
    # # Use a Safaricom phone number that you have access to, for you to be able to view the prompt.
    # phone_number = ''
    # amount = 1
    # account_reference = 'reference'
    # transaction_desc = 'Description'
    # callback_url = 'https://api.darajambili.com/express-payment'
    # response = cl.stk_push(phone_number, amount, account_reference, transaction_desc, callback_url)
    # print(f"==> {response}")
    return render(request, 'base/home.html', context)

def createPost(request):
    form = PostForm()
    author = request.user.author 

    if request.method == "POST": 
        form = PostForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            Post.objects.create(
                author = author,
                title = title,
                content = content
            )
            return redirect('forum')

    context ={"form":form}
    return render(request, 'base/post_form.html', context)

def forum(request):
    posts = Post.objects.all()
    context = {"posts":posts}
    return render(request, 'base/forum.html', context)

def readPost(request, pk):
    post = Post.objects.get(id=pk)
    comments =  post.comment_set.all() 
    userContribs = post.contributors.all()
    print(f"====> {userContribs}")
    form = CommentForm()
    author = request.user.author

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.cleaned_data['comment']
            Comment.objects.create(
                post = post,
                author = author, 
                comment = comment
            )
            post.contributors.add(request.user)
            return redirect('read-post',pk=pk)

    context = {"post":post, "form":form, "comments":comments,"contributors":userContribs}
    return render(request, 'base/post.html', context)

def recipes(request):
    recipes = Recipe.objects.all() # fetched all the recipes
    context = {"recipes":recipes}
    return render(request, 'base/recipes.html', context)

@login_required(login_url="login")
def recipe(request, pk):
    recipe = Recipe.objects.get(id=pk) 
    context = {'recipe':recipe}
    return render(request, 'base/recipe.html',context)



"""
We are now starting the CRUD operations by this we mean Create Read Update and Delete
 """
@login_required(login_url="login")
def createRecipe(request):
    form = RecipeForm()  # inialization
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            form.save() 
            return redirect('recipes') 
    context = {'form': form,"from":"create"}
    return render(request,'base/recipe_form.html', context)

@login_required(login_url="login")
def updateRecipe(request, pk):
    recipe = Recipe.objects.get(id=pk)
    form = RecipeForm(instance=recipe)
    if request.method == 'POST':
        form = RecipeForm(request.POST, instance =recipe)
        form.save()
        return redirect('recipes')

    context = {'form': form,"from":"update"}
    return render(request,'base/recipe_form.html', context)


def buyRecipe(request, pk):
    recipe = Recipe.objects.get(id=pk)
    context = { "recipe":recipe}
    if request.method == "POST": 
        phoneNumber = request.POST.get('phone')
        cl = MpesaClient() 
        phone_number = phoneNumber
        amount = 1 #int(recipe.price)
        account_reference = 'reference'
        transaction_desc = 'Description'
        callback_url = 'https://api.darajambili.com/express-payment'
        response = cl.stk_push(phone_number, amount, account_reference, transaction_desc, callback_url)
        # return HttpResponse(response)
        print(f"==> res: {response}")
        messages.info(request, f"STATUS: {response}")

    return render(request, 'base/payment_form.html', context)


# read all from the DB
def shops(request):
    shops = Shop.objects.all()
    context = {"shops":shops}
    return render(request, 'base/shops.html', context)

# Read one from the DB
def shop(request, pk):
    shop = Shop.objects.get(id=pk)
    context = {"shop": shop}
    return render(request, 'base/shop.html', context)

# update target item

@login_required(login_url="login")
def updateShop(request, pk):
    shop = Shop.objects.get(id=pk)
    form = ShopForm(instance= shop)
    if request.method == 'POST':
        form = ShopForm(request.POST, instance = shop)
        form.save()
        return redirect('shops')
    context = {"form":form}
    return render(request, 'base/shop_form.html', context)

# Delete item

@login_required(login_url="login")
def deleteShop(request, pk):
    shop = Shop.objects.get(id=pk)
    context ={"shop":shop}
    if request.method == "POST":
        shop.delete()
        return redirect('shops')
    return render(request, 'base/delete_form.html', context)

# Create operation => POST

@login_required(login_url="login")
def createShop(request):
    form = ShopForm() # instance of the shop form
    if request.method =='POST':
        form = ShopForm(request.POST)
        if form.is_valid():
            form.save() # create the data in DB
            return redirect('shops')
            
    context = {"form":form} 
    return render(request, 'base/shop_form.html', context)

@login_required(login_url="login")
def cart(request):
    return render(request, 'base/cart.html')

def about(request):
    return render(request, 'base/about.html')

base/templates/base/about.html
{% extends 'main.html'%}
{% block content%}
  <!-- Page Header Start -->
  <div class="container-fluid page-header py-6 wow fadeIn" data-wow-delay="0.1s">
    <div class="container text-center pt-5 pb-3">
        <h1 class="display-4 text-white animated slideInDown mb-3">About</h1>
        <nav aria-label="breadcrumb animated slideInDown">
            <ol class="breadcrumb justify-content-center mb-0">
                <li class="breadcrumb-item"><a class="text-white" href="{% url 'home' %}">Home</a></li> 
                <li class="breadcrumb-item text-primary active" aria-current="page">About</li>
            </ol>
        </nav>
    </div>
</div>
<!-- Page Header End -->
{% endblock content %}

base/templates/base/abstract.html
{% extends 'main.html'%} {% block content%} 
    <!-- Page Header Start -->
    <div class="container-fluid page-header py-6 wow fadeIn" data-wow-delay="0.1s">
        <div class="container text-center pt-5 pb-3">
            <h1 class="display-4 text-white animated slideInDown mb-3">create with abstract to access discounts</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a class="text-white" href="{% url 'home' %}">back</a></li> 
                    <li class="breadcrumb-item text-primary active" aria-current="page">Login</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->
<form method="POST" class=" border border-primary justify-content-center text-dark p-2 m-2">
  {% csrf_token %}
  {{form}}
</form>

{% endblock content %}

base/templates/base/auth.html
{% extends 'main.html'%} {% block content%}
<div>AUTH</div>
<hr />

<form method="POST">
    {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">User Name</label>
    <input type="text" class="form-control" name="username" />
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input
      type="password"
      class="form-control"
      name="password"
      id="exampleInputPassword1"
    />
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

base/templates/base/comment_form.html
 {% block content%} 
<form method="POST" class="container my-4 ">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="send" />
</form>

{% endblock content %}

base/templates/base/delete_form.html
{% extends 'main.html'%} {% block content%} 
<form method="POST" class="container my-4 ">
  {% csrf_token %}
  <div class="d-flex"> 
    <a class="badge bg-success py-2 px-3 m-2 " href="{{request.META.HTTP_REFERER}}">I am not sure about this</a>
    <input type="submit" value="delete"/> 
    <div>
</form>

{% endblock content %}

base/templates/base/delete_item.html
{% extends 'main.html'%} {% block content%}
<div class="container my-4">
  <div>Recipe</div>

  <form method="POST" class=" ">
    {% csrf_token %}
    <p>Are you sure you want to delete {{obj}}?</p>
    <a href="{{request.META.HTTP_REFERER}}">go back</a>
    <input type="submit" value="Confirm" />
  </form>
</div>
{% endblock content %}

base/templates/base/forum.html
{% extends 'main.html'%}
{% block content%}
    <!-- Page Header Start -->
    <div class="container-fluid page-header py-6 wow fadeIn" data-wow-delay="0.1s">
        <div class="container text-center pt-5 pb-3">
            <h1 class="display-4 text-white animated slideInDown mb-3">Forum</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a class="text-white" href="{% url 'home' %}">Home</a></li> 
                    <li class="breadcrumb-item text-primary active" aria-current="page">Forum</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->
<div class="container my-4">

    <a class="badge bg-warning text-dark text-decoration-none p-2 " href="{% url 'create-post'%}">Create Post </a>

    {% for post in posts %}
    <a class="mt-2 text-decoration-none " href="{% url 'read-post' post.id %}"><h2>{{post.title }}</h2> </a>
    <hr>
    {% endfor %}
    
</div>
{% endblock content %}

base/templates/base/login.html
{% extends 'main.html'%}

{% block content%}
    <!-- Page Header Start -->
    <div class="container-fluid page-header py-6 wow fadeIn" data-wow-delay="0.1s">
      <div class="container text-center pt-5 pb-3">
          <h1 class="display-4 text-white animated slideInDown mb-3">Login to access discounts</h1>
          <nav aria-label="breadcrumb animated slideInDown">
              <ol class="breadcrumb justify-content-center mb-0">
                  <li class="breadcrumb-item"><a class="text-white" href="{% url 'home' %}">back</a></li> 
                  <li class="breadcrumb-item text-primary active" aria-current="page">Login</li>
              </ol>
          </nav>
      </div>
  </div>
  <!-- Page Header End -->
<form method="POST" class="border border-primary justify-content-center  ">
    {% csrf_token %}
    <div class="form-group w-50">
      <label >User Name</label>
      <input type="text" class="form-control item" name="username" id="exampleInputUserName"  placeholder="Enter user name">
     </div>
    <div class="form-group my-2 w-50">
      <label>Password</label>
      <input type="password" class="form-control item" name="password" id="exampleInputPassword1" placeholder="Password">
    </div> 
    <div class="row g-3">
      <div class="col-md-6">
          <div class="form-floating">
              <input type="text" class="form-control" id="name" placeholder="Your Name">
              <label for="name">Your Name</label>
          </div>
      </div>
      <div class="col-md-6">
          <div class="form-floating">
              <input type="email" class="form-control" id="email" placeholder="Your Email">
              <label for="email">Your Email</label>
          </div>
      </div>

    <div><a href="{% url 'register' %}" class="text-primary">don't have an account? </a></div>

    <button type="submit" class="btn btn-block bg-primary">login</button>
  </form>
{% endblock %}

base/templates/base/logout_form.html
{% extends 'main.html'%} {% block content%} 
<div class="container-fluid page-header py-6 wow fadeIn" data-wow-delay="0.1s">
  <div class="container text-center pt-5 pb-3">
      <h1 class="display-4 text-white animated slideInDown mb-3">Logout</h1>
      <nav aria-label="breadcrumb animated slideInDown">
          <ol class="breadcrumb justify-content-center mb-0">
              <li class="breadcrumb-item"><a class="text-white" href="{% url 'home' %}">Home</a></li>  
              <li class="breadcrumb-item text-primary active" aria-current="page">Logout</li>
          </ol>
          <ul>
            {% if from == 'create '%}
            <ol class="breadcrumb justify-content-center mb-0"><li class="breadcrumb-item"><a class="text-white" href="{% url 'create-recipe' %}">Create New Recipe</a></li> 
            {% endif %}
            </ol> 
          {% comment %} <a href="{% url 'create-recipe' %}" class="btn btn-primary rounded-pill py-3 px-5 col-4">Create New Recipe</a> {% endcomment %}
      </nav>
  </div>
</div>
<form method="POST" class="container my-4 ">
  {% csrf_token %}
  <div class="d-flex gap-3 justify-content-center "> 
    <div><a class="btn btn-block bg-dark text-light " href="{{request.META.HTTP_REFERER}}">I do not want to log out yet!</a></div>
    <button type="submit" class="btn btn-block bg-primary"> logout</button>
    <div>
</form>

{% endblock content %}

base/templates/base/payment_form.html
{% extends 'main.html'%}
 {% block content%} 
 <!-- Page Header Start -->
 <div class="container-fluid page-header py-6 wow fadeIn" data-wow-delay="0.1s">
  <div class="container text-center pt-5 pb-3">
      <h1 class="display-4 text-white animated slideInDown mb-3">Purchase</h1>
      <nav aria-label="breadcrumb animated slideInDown">
          <ol class="breadcrumb justify-content-center mb-0">
              <li class="breadcrumb-item"><a class="text-white" href="{% url 'home' %}">Home</a></li> 
              <li class="breadcrumb-item " ><a class="text-white" href="{% url 'recipes' %}">Recipes</a></li>
              <li class="breadcrumb-item text-primary active" aria-current="page">Purchase {{recipe.name}}</li>
          </ol>
          <ul>
            {% if from == 'create '%}
            <ol class="breadcrumb justify-content-center mb-0"><li class="breadcrumb-item"><a class="text-white" href="{% url 'create-recipe' %}">Create New Recipe</a></li> 
            {% endif %}
            </ol> 
          {% comment %} <a href="{% url 'create-recipe' %}" class="btn btn-primary rounded-pill py-3 px-5 col-4">Create New Recipe</a> {% endcomment %}
      </nav>
  </div>
</div>
<!-- Page Header End -->
<div class="registration-form ">
  <form method="POST" class="border border-primary">

  {% csrf_token %}   
  <h1 class=" text-dark animated slideInDown text-center mb-3">Buy {{recipe.name}} Recipe </h1>
  {% comment %} {% for field in form  %} {% endcomment %}
  <div class="form-floating">
    {{field}}
    <input  type="tel" 
    name="phone" class="form-control"  placeholder="Enter Phone Number">
    <small class="text-success text-center py-2">we will give you an mpesa prompt to pay KsH.{{recipe.price}}</small>
    <label  >Enter Phone Number( eg. 07123456789):</label>
</div>
<button type="submit" class="btn btn-block bg-dark text-light my-2 mx-auto"> pay </button>
       
  {% comment %} {% endfor %}
      <div class="form-group">
        {% if from == 'create' %}
          <button type="submit" class="btn btn-block bg-primary">Create Recipe</button>
          {% else %}
          <button type="submit" class="btn btn-block bg-primary">Update Recipe</button>

        {% endif %} {% endcomment %}
      </div>
  </form> 
</div>
 
</div> 

{% endblock content %}

base/templates/base/recipe.html
{% extends 'main.html'%} {% block content%}
 <!-- Page Header Start -->
 <div class="container-fluid page-header py-6 wow fadeIn" data-wow-delay="0.1s">
  <div class="container text-center pt-5 pb-3">
      <h1 class="display-4 text-white animated slideInDown mb-3">Recipes</h1>
      <nav aria-label="breadcrumb animated slideInDown">
          <ol class="breadcrumb justify-content-center mb-0">
              <li class="breadcrumb-item"><a class="text-white" href="{% url 'home' %}">Home</a></li> 
              <li class="breadcrumb-item " ><a class="text-white" href="{% url 'recipes' %}">Recipes</a></li>
              <li class="breadcrumb-item text-primary active" aria-current="page">{{recipe.name}}</li>
          </ol>
          <ul>
            <ol class="breadcrumb justify-content-center mb-0"><li class="breadcrumb-item"><a class="text-white" href="{% url 'create-recipe' %}">Create New Recipe</a></li> 
            </ol> 
          {% comment %} <a href="{% url 'create-recipe' %}" class="btn btn-primary rounded-pill py-3 px-5 col-4">Create New Recipe</a> {% endcomment %}
      </nav>
  </div>
</div>
<!-- Page Header End -->
<div class="container my-2 fs-6">

  <div class="d-flex gap-2">
    <div class=" border border-primary my-auto text-center text-dark rounded-pill px-3 py-2 ">KsH. {{recipe.price}}</div>
  <a class="badge  my-auto text-center  bg-primary  text-dark rounded-pill  px-3 py-2 " href="{% url 'buy-recipe' recipe.id %}">buy me</a>
  </div>
  <h1>{{recipe.name}}                
  </h1> 
  <p class="text-dark">
    Level: <span class="badge bg-dark text-primary p-2">{{recipe.get_level_display}}</span>
    <br />
    {{recipe.decription}}
  </p>
  <h2>Ingredients</h2>
  <p class="text-dark">{{recipe.ingredients}}</p>
  <h2>Instructions</h2>
  <p class="text-dark">{{recipe.steps}}</p>

  <a href="{% url 'update-recipe' recipe.id %}" class="badge text-dark bg-warning my-2 p-2">Edit me</a>
</div>

{% endblock content %}

base/templates/base/shops.html
{% extends 'main.html'%}
{% block content%}
<div class="">
      <!-- Page Header Start -->
      <div class="container-fluid page-header py-6 wow fadeIn" data-wow-delay="0.1s">
        <div class="container text-center pt-5 pb-3">
            <h1 class="display-4 text-white animated slideInDown mb-3">Shops</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a class="text-white" href="{% url 'home' %}">Home</a></li> 
                    <li class="breadcrumb-item text-primary active" aria-current="page">Shops</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->
<a class= "badge bg-info text-dark px-2 py-2 my-2" href="{% url 'create-shop' %}"> add product</a>
{% for item in shops %}
<h6>
<a href="{% url 'shop' item.id %}"> {{item}}</a> </h6>
{% endfor %} </div>
{% endblock content %}

base/templates/base/user_profile.html
{% extends 'main.html'%}
{% block content%}
<div class="container my-4 ">

    <div>
        {{author.user.username}}
        </div>
        <hr>   
       <p class='text-break'> {{author.bio }}</p>
        </div>
        <div>

        <div class="container">
            <h1>POSTS</h1>

<hr>

            {% for post in posts %}

            <h2>{{post.title}}</h2> 
            {% endfor %}
        </div>
</div>

{% endblock content %}